/**
 * HQ Dashboard Mock Data
 * Comprehensive mock data for all HQ modules
 */

import type {
  GlobalKPIs,
  Region,
  Sensor,
  SensorStats,
  HQVehicle,
  HQReport,
  AIPrediction,
  SystemAlert,
  HQUser,
} from '@/types/hq';

// Global KPIs
export const mockGlobalKPIs: GlobalKPIs = {
  regions: {
    total: 24,
    active: 22,
    critical: 2,
  },
  cities: {
    total: 156,
    active: 148,
    monitored: 156,
  },
  users: {
    total: 45678,
    admins: 234,
    drivers: 1234,
    users: 44210,
    online: 12456,
  },
  bins: {
    total: 23456,
    active: 22134,
    full: 2345,
    offline: 1322,
    avgFillLevel: 64,
  },
  vehicles: {
    total: 567,
    onRoute: 423,
    idle: 132,
    maintenance: 12,
  },
  reports: {
    total: 8934,
    pending: 456,
    resolved: 8234,
    todayCount: 123,
    resolutionRate: 92,
  },
};

// Regions
export const mockRegions: Region[] = [
  {
    id: 'RGN-001',
    name: 'North Delhi',
    city: 'Delhi',
    country: 'India',
    coordinates: { lat: 28.7041, lng: 77.1025 },
    avgFillLevel: 68,
    activeDrivers: 45,
    reportsPending: 23,
    sensorHealth: 94,
    healthScore: 87,
    performance: 'Excellent',
    totalBins: 1234,
    activeBins: 1189,
    vehicles: 34,
    population: 2500000,
  },
  {
    id: 'RGN-002',
    name: 'South Mumbai',
    city: 'Mumbai',
    country: 'India',
    coordinates: { lat: 18.9220, lng: 72.8347 },
    avgFillLevel: 72,
    activeDrivers: 56,
    reportsPending: 34,
    sensorHealth: 89,
    healthScore: 82,
    performance: 'Good',
    totalBins: 1567,
    activeBins: 1498,
    vehicles: 42,
    population: 3200000,
  },
  {
    id: 'RGN-003',
    name: 'Bangalore Central',
    city: 'Bangalore',
    country: 'India',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    avgFillLevel: 58,
    activeDrivers: 38,
    reportsPending: 12,
    sensorHealth: 96,
    healthScore: 91,
    performance: 'Excellent',
    totalBins: 987,
    activeBins: 965,
    vehicles: 28,
    population: 1800000,
  },
  {
    id: 'RGN-004',
    name: 'Pune West',
    city: 'Pune',
    country: 'India',
    coordinates: { lat: 18.5204, lng: 73.8567 },
    avgFillLevel: 81,
    activeDrivers: 29,
    reportsPending: 45,
    sensorHealth: 76,
    healthScore: 65,
    performance: 'Fair',
    totalBins: 756,
    activeBins: 698,
    vehicles: 21,
    population: 1200000,
  },
  {
    id: 'RGN-005',
    name: 'Hyderabad East',
    city: 'Hyderabad',
    country: 'India',
    coordinates: { lat: 17.3850, lng: 78.4867 },
    avgFillLevel: 89,
    activeDrivers: 22,
    reportsPending: 67,
    sensorHealth: 68,
    healthScore: 58,
    performance: 'Poor',
    totalBins: 645,
    activeBins: 589,
    vehicles: 18,
    population: 980000,
  },
];

// Sensors
export const mockSensors: Sensor[] = [
  {
    id: 'SNS-1001',
    binId: 'BIN-001',
    location: 'Connaught Place, Delhi',
    status: 'Active',
    fillLevel: 85,
    lastUpdated: '2024-10-19T16:45:00Z',
    dataDelay: 2,
    battery: 87,
    temperature: 28,
    coordinates: { lat: 28.6315, lng: 77.2167 },
  },
  {
    id: 'SNS-1002',
    binId: 'BIN-002',
    location: 'Marine Drive, Mumbai',
    status: 'Active',
    fillLevel: 45,
    lastUpdated: '2024-10-19T16:44:00Z',
    dataDelay: 3,
    battery: 92,
    temperature: 31,
    coordinates: { lat: 18.9432, lng: 72.8236 },
  },
  {
    id: 'SNS-1003',
    binId: 'BIN-003',
    location: 'MG Road, Bangalore',
    status: 'Offline',
    fillLevel: 62,
    lastUpdated: '2024-10-19T14:20:00Z',
    dataDelay: 145,
    battery: 12,
    temperature: 26,
    coordinates: { lat: 12.9762, lng: 77.6033 },
  },
  {
    id: 'SNS-1004',
    binId: 'BIN-004',
    location: 'FC Road, Pune',
    status: 'Faulty',
    fillLevel: 0,
    lastUpdated: '2024-10-19T16:30:00Z',
    dataDelay: 15,
    battery: 45,
    temperature: 0,
    coordinates: { lat: 18.5314, lng: 73.8446 },
  },
  {
    id: 'SNS-1005',
    binId: 'BIN-005',
    location: 'Banjara Hills, Hyderabad',
    status: 'Maintenance',
    fillLevel: 30,
    lastUpdated: '2024-10-19T16:40:00Z',
    dataDelay: 5,
    battery: 78,
    temperature: 29,
    coordinates: { lat: 17.4239, lng: 78.4738 },
  },
];

export const mockSensorStats: SensorStats = {
  total: 23456,
  active: 22134,
  offline: 1089,
  faulty: 156,
  maintenance: 77,
  avgResponseTime: 3.2,
};

// Vehicles
export const mockVehicles: HQVehicle[] = [
  {
    id: 'VEH-001',
    vehicleNumber: 'DL-01-AB-1234',
    driverName: 'Rajesh Kumar',
    driverId: 'DRV-001',
    region: 'North Delhi',
    status: 'On Route',
    capacityUsed: 78,
    routeName: 'Route A - Central Delhi',
    currentLocation: { lat: 28.6519, lng: 77.2315 },
    lastUpdated: '2024-10-19T16:45:00Z',
    todayCollections: 34,
    efficiency: 92,
  },
  {
    id: 'VEH-002',
    vehicleNumber: 'MH-02-CD-5678',
    driverName: 'Amit Patel',
    driverId: 'DRV-002',
    region: 'South Mumbai',
    status: 'On Route',
    capacityUsed: 65,
    routeName: 'Route B - South Mumbai',
    currentLocation: { lat: 18.9220, lng: 72.8347 },
    lastUpdated: '2024-10-19T16:44:00Z',
    todayCollections: 28,
    efficiency: 88,
  },
  {
    id: 'VEH-003',
    vehicleNumber: 'KA-03-EF-9012',
    driverName: 'Suresh Reddy',
    driverId: 'DRV-003',
    region: 'Bangalore Central',
    status: 'Idle',
    capacityUsed: 0,
    currentLocation: { lat: 12.9716, lng: 77.5946 },
    lastUpdated: '2024-10-19T16:30:00Z',
    todayCollections: 42,
    efficiency: 95,
  },
  {
    id: 'VEH-004',
    vehicleNumber: 'MH-12-GH-3456',
    driverName: 'Vikram Singh',
    driverId: 'DRV-004',
    region: 'Pune West',
    status: 'Maintenance',
    capacityUsed: 0,
    currentLocation: { lat: 18.5204, lng: 73.8567 },
    lastUpdated: '2024-10-19T10:00:00Z',
    todayCollections: 0,
    efficiency: 0,
  },
];

// Reports
export const mockReports: HQReport[] = [
  {
    id: 'REP-001',
    userId: 'USR-001',
    userName: 'Priya Sharma',
    region: 'North Delhi',
    category: 'Full Bin',
    priority: 'High',
    status: 'Pending',
    description: 'Bin overflowing at Connaught Place',
    location: 'Connaught Place, Delhi',
    createdAt: '2024-10-19T15:30:00Z',
  },
  {
    id: 'REP-002',
    userId: 'USR-002',
    userName: 'Rahul Verma',
    region: 'South Mumbai',
    category: 'Damage',
    priority: 'Medium',
    status: 'Assigned',
    description: 'Broken bin lid at Marine Drive',
    location: 'Marine Drive, Mumbai',
    assignedTo: 'Maintenance Team A',
    createdAt: '2024-10-19T14:20:00Z',
  },
  {
    id: 'REP-003',
    userId: 'USR-003',
    userName: 'Anjali Desai',
    region: 'Bangalore Central',
    category: 'Missed Pickup',
    priority: 'Low',
    status: 'Resolved',
    description: 'Scheduled pickup was missed',
    location: 'MG Road, Bangalore',
    assignedTo: 'Operations Team',
    createdAt: '2024-10-18T10:00:00Z',
    resolvedAt: '2024-10-19T09:00:00Z',
    resolutionTime: 23,
  },
  {
    id: 'REP-004',
    userId: 'USR-004',
    userName: 'Karthik Iyer',
    region: 'Pune West',
    category: 'Sensor Issue',
    priority: 'Critical',
    status: 'In Progress',
    description: 'Sensor not responding',
    location: 'FC Road, Pune',
    assignedTo: 'Tech Team',
    createdAt: '2024-10-19T16:00:00Z',
  },
];

// AI Predictions
export const mockPredictions: AIPrediction[] = [
  {
    id: 'PRED-001',
    type: 'Overflow',
    region: 'North Delhi',
    location: 'Connaught Place Zone',
    confidence: 94,
    predictedTime: '2024-10-20T10:00:00Z',
    severity: 'High',
    recommendation: 'Schedule immediate pickup for 5 bins in this zone',
    affectedAssets: ['BIN-001', 'BIN-002', 'BIN-003', 'BIN-004', 'BIN-005'],
  },
  {
    id: 'PRED-002',
    type: 'Route Inefficiency',
    region: 'South Mumbai',
    location: 'Marine Drive Route',
    confidence: 87,
    predictedTime: '2024-10-20T08:00:00Z',
    severity: 'Medium',
    recommendation: 'Optimize route to reduce travel time by 25%',
    affectedAssets: ['VEH-002', 'ROUTE-B'],
  },
  {
    id: 'PRED-003',
    type: 'Sensor Anomaly',
    region: 'Bangalore Central',
    location: 'MG Road Sector',
    confidence: 78,
    predictedTime: '2024-10-19T20:00:00Z',
    severity: 'Low',
    recommendation: 'Check sensor battery levels in next maintenance cycle',
    affectedAssets: ['SNS-1003', 'SNS-1006', 'SNS-1009'],
  },
  {
    id: 'PRED-004',
    type: 'Maintenance',
    region: 'Pune West',
    location: 'Vehicle Fleet',
    confidence: 91,
    predictedTime: '2024-10-22T00:00:00Z',
    severity: 'Critical',
    recommendation: 'Schedule preventive maintenance for 3 vehicles',
    affectedAssets: ['VEH-004', 'VEH-007', 'VEH-009'],
  },
];

// System Alerts
export const mockAlerts: SystemAlert[] = [
  {
    id: 'ALT-001',
    type: 'Overflow',
    severity: 'Critical',
    title: 'Multiple Bins Near Capacity',
    message: '5 bins in North Delhi are above 90% capacity',
    region: 'North Delhi',
    timestamp: '2024-10-19T16:45:00Z',
    read: false,
    actionRequired: true,
    actionUrl: '/hq/regions/RGN-001',
  },
  {
    id: 'ALT-002',
    type: 'Vehicle Delay',
    severity: 'Warning',
    title: 'Vehicle Behind Schedule',
    message: 'VEH-002 is 45 minutes behind schedule',
    region: 'South Mumbai',
    timestamp: '2024-10-19T16:30:00Z',
    read: false,
    actionRequired: true,
    actionUrl: '/hq/vehicles',
  },
  {
    id: 'ALT-003',
    type: 'Sensor Offline',
    severity: 'Error',
    title: 'Sensor Connection Lost',
    message: '12 sensors offline in Bangalore Central',
    region: 'Bangalore Central',
    timestamp: '2024-10-19T16:15:00Z',
    read: true,
    actionRequired: true,
    actionUrl: '/hq/iot',
  },
  {
    id: 'ALT-004',
    type: 'Report Escalation',
    severity: 'Warning',
    title: 'Unresolved Critical Report',
    message: 'Critical report pending for 4 hours',
    region: 'Pune West',
    timestamp: '2024-10-19T16:00:00Z',
    read: false,
    actionRequired: true,
    actionUrl: '/hq/reports',
  },
  {
    id: 'ALT-005',
    type: 'System',
    severity: 'Info',
    title: 'System Backup Completed',
    message: 'Daily backup completed successfully',
    region: 'All Regions',
    timestamp: '2024-10-19T15:00:00Z',
    read: true,
    actionRequired: false,
  },
];

// HQ Users
export const mockHQUsers: HQUser[] = [
  {
    id: 'HQU-001',
    name: 'Vikram Patel',
    email: 'vikram.patel@nodesio.com',
    role: 'Super Admin',
    status: 'Active',
    lastLogin: '2024-10-19T16:45:00Z',
    sessionTime: 245,
    permissions: ['all'],
  },
  {
    id: 'HQU-002',
    name: 'Anjali Mehta',
    email: 'anjali.mehta@nodesio.com',
    role: 'Regional Admin',
    status: 'Active',
    region: 'North India',
    lastLogin: '2024-10-19T16:30:00Z',
    sessionTime: 180,
    permissions: ['view', 'edit', 'manage_region'],
  },
  {
    id: 'HQU-003',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@nodesio.com',
    role: 'Analyst',
    status: 'Active',
    lastLogin: '2024-10-19T15:00:00Z',
    sessionTime: 320,
    permissions: ['view', 'analytics', 'export'],
  },
  {
    id: 'HQU-004',
    name: 'Priya Singh',
    email: 'priya.singh@nodesio.com',
    role: 'Operator',
    status: 'Active',
    lastLogin: '2024-10-19T14:30:00Z',
    sessionTime: 150,
    permissions: ['view', 'update_status'],
  },
  {
    id: 'HQU-005',
    name: 'Karthik Reddy',
    email: 'karthik.reddy@nodesio.com',
    role: 'Regional Admin',
    status: 'Inactive',
    region: 'South India',
    lastLogin: '2024-10-15T10:00:00Z',
    sessionTime: 0,
    permissions: ['view', 'edit', 'manage_region'],
  },
];

export const simulateDelay = (ms: number = 500) =>
  new Promise((resolve) => setTimeout(resolve, ms));
